### ISSUE TITLE
Add essential fields into info column

### ISSUE THREAD

**Issue by bananaappletw** [deror1869107/omniauth-nctu#1]
For now, only `email` field in the `info` column.
Many OAuth provider implement essential information in the `info` column.
For example, `omniauth-facebook` 
```
 info: {
    email: 'joe@bloggs.com',
    name: 'Joe Bloggs',
    first_name: 'Joe',
    last_name: 'Bloggs',
    image: 'http://graph.facebook.com/1234567/picture?type=square',
    verified: true
  },
```
In my opinion, you could use `uid` as `name` and maybe `nctu logo` as `image` field.
Then, developer could use the same logic for different OAuth providers.

**Comment by yysung1123** [comment]
Is there any nctu logo url from NCTU's official websites?

**Comment by bananaappletw** [comment]
@deror1869107 
How do you think this [one](http://museum.lib.nctu.edu.tw/share/mark.gif)?

**Comment by yysung1123** [comment]
Great!

**Comment by yysung1123** [comment]
#2 Add uid and image fields

**Comment by bananaappletw** [comment]
@deror1869107 Thanks

**Comment by bananaappletw** [comment]
@deror1869107  It's better to change `uid` to `name` in `info` hash.

**Comment by bananaappletw** [comment]
@deror1869107 Could you release the new version of `omniauth-nctu`?

**Comment by yysung1123** [comment]
New Version of ```omniauth-nctu``` has been pushed to rubygems.org !
